* Module Overview

This module's programs are once again much shorter than those from HtDW and
Compound.

The video this module range in length. But there isn't a half hour one!  As
before, the longer ones are mostly just a step-by-step working through of a
problem, so while it takes time to watch, it isn't all new content.

In this module we take a small but very significant step in terms of the
complexity of the information we can represent as data. We will start to have
designs with more than one data definition each for representing one part of the
overall information. As we have seen before this difference will arise in the
information, be reflected in the type comments, be carried into the templates by
the templates rules and show up in the structure of the final definitions and
tests.

Working through the videos and practice materials for this module should take a
approximately 4-6 hours of dedicated time to complete.


* Learning Goal

- Be able to predict and identify the correspondence between references in a
  data definition and helper function calls in functions that operate on the
  data.
