* How to Design Functions

This module is where this course starts to differs from other introductory
programming courses--we are going to start learning the design method, and this
should be new material even for people who hve programmed before.

* Learning Goals

- Be able to use the How to Design Functions (HtDF) recipe to design function
  that operate on primitive data.

- Be able to read a complete function design and identify its different
  elements.

- Be able to evaluate the different elements for clarity, simplicity and
  consistency with each other.

- Be able to evaluate the entire design for how well it solves the given
  problem.

* Hints About this Material

We repeated the advice that this is material you learn by doing; for each video
you should download the starter file and type along with the video. Or you can
pause the video occasionally and try to work ahead, then restart the video and
compare what you did to what happened in the video.

* Planning Your Time

Working through the videos and practice materials for this module should take
approximately 4-7 hours of dedicated time to complete.

NOTE: To help you master the design method, much of the video material consists
of the instructor working through a complete design step-by-step. As a result,
in most of the videos, at least part of the material is essentially review, with
new points interspersed throughout. We could have made this videos shorter by
just including the 'new parts' for each video. But students have told us that it
is more helpful to see the new material in context, as part of complete design
problem. So, in most videos, some of the material will be review and some of it
will be new. This means, there are more minutes of video than there are minutes
of new materials.

  
